[package]
name = "lsdiff-rs"
version = "0.1.2"
authors = ["hedgar2017 <hedgar2017@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Rust lsdiff implementation"

[dependencies]
clap = "2.32.0"
failure = "0.1.5"
